name = "NumberRepresentation"
uuid = "555dd0a5-fa5e-44e8-9057-a9c9c7431516"
version = "0.5.0"
authors = ["Rafael Alves Batista <rafaelab@users.noreply.github.com>"]

[deps]
NumericIO = "6c575b1c-77cb-5640-a5dc-a54116c90507"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"

[weakdeps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[extensions]
NumberRepresentationMakieRichTextExt = "Makie"

[compat]
NumericIO = "0.3.3"
Printf = "1.11.0"
Requires = "1.3.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
